### ISSUE TITLE
calibre.ebooks.mobi.MobiError: Unknown book type

### ISSUE THREAD

**Issue by raindrop213** [meokisama/UnpackKindleS#1]
platform: amazon.co.jp
calibre: 7.16
kindle for pc: 2.4.1 (70946)

Change "HandleAZW3.bat" path
```
@echo off
setlocal enabledelayedexpansion
set "parent_folder=C:\Users\RD2B\Documents\My Kindle Content"
```

Error
```
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 267, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 502, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 267, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 502, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x81\x8b\xde\x01\x93\x8c"\x08'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 267, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 502, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x81\x8b\xde\x01\x93\x8c"\x08'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 267, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 502, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x81\x8b\xde\x01\x93\x8c"\x08'
```

**Comment by meokisama** [comment]
In Kindle PC version 2.4, the resource file (.azw.res) is divided into 3 smaller files, causing the aforementioned error. You should use version 2.0 or 2.1, where each ebook only has 2 files ( ___.azw and ___.azw.res ).

**Comment by raindrop213** [comment]
now, The program ran successfully and was able to import into Calibre, but while some books can be successfully decrypted, most books cannot be decrypted.

kindle for pc: 2.0

**Comment by meokisama** [comment]
I only use this tool to convert light novels to EPUB. I don't know if other books have any issues, but have you installed the DeDRM plugin for Calibre? (https://github.com/noDRM/DeDRM_tools)

**Comment by raindrop213** [comment]
Since I had been using the original UnpackKindleS before, I hadn't installed Calibre plugins. Now that I've installed them, the DeDRM process has been successful. Thank you very much! 

However, there's still a problem with retrieving the original images; the extracted versions are all compressed. Is there a solution for this issue?

DeDEM: 10.0.9

**Comment by meokisama** [comment]
>Since I had been using the original UnpackKindleS before, I hadn't installed Calibre plugins 

That's because my batch file uses Calibre to automate the conversion from AZW to AZW3 in the background, so you'll need to deDRM for this case

> the extracted versions are all compressed

I don't quite understand what you're saying

**Comment by raindrop213** [comment]
If the file contains "______.azw.res", the program is unable to restore the original images from it. The final output is a smaller version, not the original file.

However, it seems to be a problem with the Calibre plugin, I guess.

**Comment by meokisama** [comment]
I haven't encountered that issue. When I use this tool, the resulting EPUB file is around 10MB, whereas if I convert directly from AZW to EPUB using Calibre, the file size is only about 2-3MB.

![image](https://github.com/user-attachments/assets/414fcd85-e7dd-4773-b3a3-23d3d49d212f)

**Comment by raindrop213** [comment]
I solved the problem manually.
My operation process is as follows:

1. When I download a Kindle eBook, I get the file "B01DK0TRFK_EBOK" which includes:
B01DK0TRFK_EBOK.apnx
B01DK0TRFK_EBOK.azw
B01DK0TRFK_EBOK.mbpV2
CR!KYSQKTKPCH6VXE2CVYCKPN4P6XPV.azw.res

2. When I run the "_Tool_Proc_MyKindleContent.bat" script, it successfully converts the book to AZW3 and imports it into Calibre, but it doesn't automatically import it into the "B01DK0TRFK_EBOK" folder. Then, I encounter the following error:
```
H:\qBit\tools\UnpackKindleS-master\app>"H:\qBit\tools\UnpackKindleS-master\\AZW3_PC_DeDRM.exe" "C:\Users\RD2B\Documents\My Kindle Content\B01DK0TRFK_EBOK\B01DK0TRFK_EBOK.azw"
Traceback (most recent call last):
  File "AZW3_PC_DeDRM.py", line 6, in <module>
  File "e:\apptemp\pip-install-9qp7ma\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 391, in load_module
  File "mobidedrm.py", line 83, in <module>
LookupError: unknown encoding: cp65001
[3440] Failed to execute script AZW3_PC_DeDRM
Cannot find .azw3 file in C:\Users\RD2B\Documents\My Kindle Content\B01DK0TRFK_EBOK
```


3. Then, I manually drag the AZW3 file from Calibre into the "B01DK0TRFK_EBOK" folder and run the "_Tool_Drop_Single.bat" script, which successfully extracts the EPUB with HD images.

**Comment by meokisama** [comment]
I don't know why it's not working for you, but the batch file has been written to automate your manual process. I've added detailed comments as follows.

![image](https://github.com/user-attachments/assets/7e915051-e41d-4ca9-94eb-8045d3585335)

**Comment by raindrop213** [comment]
**I rewrote the program following your approach, and now it works.**
```
@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion
set "parent_folder=C:\Users\RD2B\Documents\My Kindle Content"

for /d %%A in ("%parent_folder%\*") do (
    if /i not "%%~nxA"=="NoteDocuments" (
        for %%B in ("%%A\*.azw") do (
            echo Found file: %%B

            set file_name=%%~nB
            echo File Name: !file_name!
            
            for /f "delims=" %%i in ('calibredb add "%%B" --duplicates') do (
                set output=%%i
                echo Output Line: !output!
                for /f "tokens=2 delims= " %%j in ("!output!") do (
                    set book_id=%%j
                )
            )
            echo Add Book ID: !book_id!

            calibredb export !book_id! --format azw3 --dont-asciiize --dont-save-cover --dont-write-opf --template !file_name! --to-dir "%%A"
            calibredb remove !book_id! --permanent
            echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        )
    )
)
pause
```

I suspect that the issues I encountered with exporting and deleting azw3 files were due to some problems with variable naming and function calls. It might also be related to some differences in my windows system (19045.4651).
